spring:
  application:
    name: customer-service
  profiles:
    active: dev
  main:
    keep-alive: true
  threads:
    virtual:
      enabled: true
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      indent-output: true
  flyway:
    default-schema: flyway
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    mapping-resources:
      - db/mappings/customer.orm.xml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.boot.model.internal.JPAXMLOverriddenAnnotationReader: ERROR
